// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class UserWebAutho
    {
        [Key]
        [StringLength(10)]
        public string account { get; set; }
        [Key]
        [StringLength(10)]
        public string AuthoWeb { get; set; }
        [Required]
        [StringLength(12)]
        public string AuthoIOP { get; set; }
        [Required]
        [StringLength(10)]
        public string inusr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime indt { get; set; }
        [StringLength(10)]
        public string upusr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? updt { get; set; }
    }
}