// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class UserAcc
    {
        public int id { get; set; }
        [Key]
        [StringLength(1)]
        public string manuf { get; set; }
        [Key]
        [StringLength(10)]
        public string account { get; set; }
        [Required]
        [StringLength(6)]
        public string empno { get; set; }
        [Required]
        [StringLength(50)]
        public string vname { get; set; }
        [Required]
        [StringLength(50)]
        public string passw { get; set; }
        [StringLength(1)]
        public string sex { get; set; }
        [StringLength(3)]
        public string dept { get; set; }
        [StringLength(100)]
        public string email { get; set; }
        [StringLength(60)]
        public string token { get; set; }
        [StringLength(255)]
        public string image { get; set; }
        [Column(TypeName = "date")]
        public DateTime indat { get; set; }
        [Required]
        [StringLength(5)]
        public string intime { get; set; }
        [Column(TypeName = "date")]
        public DateTime? updat { get; set; }
        [StringLength(5)]
        public string uptime { get; set; }
    }
}