// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#23567;&#32218;&#37096;&#38272;&#20998;&#32068;&#27284;
    /// </summary>
    public partial class HP_Lean_Dept_n15_4
    {
        /// <summary>
        ///         /// 廠別
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Factory_ID { get; set; }
        /// <summary>
        ///         /// &#32218;&#21029;
        /// </summary>
        [Key]
        [StringLength(3)]
        public string Lean { get; set; }
        /// <summary>
        ///         /// &#24207;&#34399;
        /// </summary>
        [Key]
        public short Seq { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;&#20195;&#34399;
        /// </summary>
        [StringLength(3)]
        public string Dept_ID { get; set; }
        /// <summary>
        ///         /// &#29983;&#25928;&#26085;
        /// </summary>
        [Key]
        [Column(TypeName = "date")]
        public DateTime Effective_Date { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(6)]
        public string HP_User { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#26085;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? HP_Date { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "time(0)")]
        public TimeSpan? HP_Time { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(50)]
        public string Update_By { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}