// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#26448;&#26009;&#20027;&#27284;
    /// </summary>
    public partial class HP_Material_j13
    {
        /// <summary>
        ///         /// 材料編號
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Material_ID { get; set; }
        /// <summary>
        ///         /// &#26448;&#26009;&#20013;&#25991;&#21517;&#31281;
        /// </summary>
        [StringLength(240)]
        public string Material_C_Name { get; set; }
        /// <summary>
        ///         /// &#26448;&#26009;&#33521;&#25991;&#21517;&#31281;
        /// </summary>
        [StringLength(240)]
        public string Material_E_Name { get; set; }
        /// <summary>
        ///         /// &#20013;&#25991;&#21934;&#20301;
        /// </summary>
        [StringLength(4)]
        public string C_Unit { get; set; }
        /// <summary>
        ///         /// &#33521;&#25991;&#21934;&#20301;
        /// </summary>
        [StringLength(4)]
        public string E_Unit { get; set; }
        /// <summary>
        ///         /// &#25505;&#36092;&#24288;&#21312;
        /// </summary>
        [StringLength(10)]
        public string Purchase_Factory { get; set; }
        /// <summary>
        ///         /// &#26448;&#26009;&#21312;&#20998;
        /// </summary>
        [StringLength(1)]
        public string Material_Type { get; set; }
        /// <summary>
        ///         /// &#25505;&#36092;&#22411;&#24907;
        /// </summary>
        [StringLength(1)]
        public string Purchase_Type { get; set; }
        /// <summary>
        ///         /// &#20272;&#37327;&#26041;&#24335;
        /// </summary>
        [StringLength(1)]
        public string Estimate_Type { get; set; }
        /// <summary>
        ///         /// &#35330;&#36092;&#21934;&#21015;&#21360;&#26684;&#24335;
        /// </summary>
        [StringLength(1)]
        public string Purchase_Print { get; set; }
        /// <summary>
        ///         /// &#23610;&#23544;&#21015;&#21360;&#21542;
        /// </summary>
        [StringLength(1)]
        public string Size_Print { get; set; }
        /// <summary>
        ///         /// &#26597;&#26009;&#21542;
        /// </summary>
        [StringLength(1)]
        public string Check_Material_YN { get; set; }
        /// <summary>
        ///         /// &#26597;&#26009;&#31561;&#32026;
        /// </summary>
        [StringLength(1)]
        public string Check_Material_Level { get; set; }
        /// <summary>
        ///         /// kg&#36681;&#25563;&#29575;
        /// </summary>
        [Column(TypeName = "decimal(9, 6)")]
        public decimal? KG_Conversion_Rate { get; set; }
        /// <summary>
        ///         /// &#36914;&#37559;&#20195;&#34399;
        /// </summary>
        [StringLength(3)]
        public string IO_No { get; set; }
        /// <summary>
        ///         /// &#20801;&#25910;&#29575;
        /// </summary>
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? Yield { get; set; }
        /// <summary>
        ///         /// &#20839;&#30418;&#22806;&#31665;&#38263;
        /// </summary>
        [Column(TypeName = "decimal(9, 1)")]
        public decimal? Out_Box_Length { get; set; }
        /// <summary>
        ///         /// &#20839;&#30418;&#22806;&#31665;&#23532;
        /// </summary>
        [Column(TypeName = "decimal(9, 1)")]
        public decimal? Out_Box_Width { get; set; }
        /// <summary>
        ///         /// &#20839;&#30418;&#22806;&#31665;&#39640;
        /// </summary>
        [Column(TypeName = "decimal(9, 1)")]
        public decimal? Out_Box_Height { get; set; }
        /// <summary>
        ///         /// &#20839;&#30418;&#22806;&#31665;&#21934;&#20301;
        /// </summary>
        [StringLength(1)]
        public string Out_Box_Unit { get; set; }
        /// <summary>
        ///         /// &#20839;&#30418;&#22806;&#31665;&#26448;&#31309;
        /// </summary>
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? Out_Box_Meas { get; set; }
        /// <summary>
        ///         /// &#20839;&#30418;&#22806;&#31665;&#21542;
        /// </summary>
        [StringLength(1)]
        public string Out_Box_YN { get; set; }
        /// <summary>
        ///         /// &#28136;&#37325;
        /// </summary>
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? Net_Weight { get; set; }
        /// <summary>
        ///         /// &#27611;&#37325;
        /// </summary>
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? Gross_Weight { get; set; }
        /// <summary>
        ///         /// &#20839;&#24115;&#20027;&#31185;&#30446;
        /// </summary>
        [StringLength(4)]
        public string Internal_Account_Main { get; set; }
        /// <summary>
        ///         /// &#20839;&#24115;&#23376;&#31185;&#30446;
        /// </summary>
        [StringLength(4)]
        public string Internal_Account_Sub { get; set; }
        /// <summary>
        ///         /// &#22806;&#24115;&#20027;&#31185;&#30446;
        /// </summary>
        [StringLength(4)]
        public string External_Account_Main { get; set; }
        /// <summary>
        ///         /// &#22806;&#24115;&#23376;&#31185;&#30446;
        /// </summary>
        [StringLength(4)]
        public string External_Account_Sub { get; set; }
        /// <summary>
        ///         /// &#26368;&#24460;&#20351;&#29992;&#38795;&#22411;
        /// </summary>
        [StringLength(15)]
        public string Last_Style { get; set; }
        /// <summary>
        ///         /// &#26368;&#24460;&#20351;&#29992;&#38991;&#33394;
        /// </summary>
        [StringLength(2)]
        public string Last_Scolor { get; set; }
        /// <summary>
        ///         /// &#26448;&#26009;&#25152;&#23660;&#23458;&#25142;&#20195;&#34399;
        /// </summary>
        [StringLength(4)]
        public string Material_Customer_No { get; set; }
        /// <summary>
        ///         /// &#20351;&#29992;&#24037;&#20855;&#39006;&#21029;
        /// </summary>
        [StringLength(10)]
        public string Tool_Class { get; set; }
        /// <summary>
        ///         /// &#27298;&#26680;&#23436;&#25104;&#21542;
        /// </summary>
        [StringLength(1)]
        public string Check_YN { get; set; }
        /// <summary>
        ///         /// &#27298;&#26680;&#23436;&#25104;&#26085;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? Check_Date { get; set; }
        /// <summary>
        ///         /// &#25505;&#36092;&#21934;&#20301;
        /// </summary>
        [StringLength(4)]
        public string Purchase_Dept_ID { get; set; }
        /// <summary>
        ///         /// &#36681;&#25563;&#29575;
        /// </summary>
        [Column(TypeName = "decimal(19, 5)")]
        public decimal? Conversion_Rate { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(6)]
        public string HP_User { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#26085;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? HP_Date { get; set; }
        /// <summary>
        ///         /// &#24246;&#21209;&#38646;&#20214;&#25152;&#23660;&#24288;&#21029;
        /// </summary>
        [StringLength(10)]
        public string Service_Parts_Factory { get; set; }
        /// <summary>
        ///         /// &#23529;&#26680;&#20154;&#21729;
        /// </summary>
        [StringLength(6)]
        public string Auditor { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(50)]
        public string Update_By { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}