// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#38795;&#22411;&#24037;&#20855;&#23610;&#23544;&#23565;&#29031;
    /// </summary>
    public partial class HP_Style_Tool_Setup_j12
    {
        /// <summary>
        ///         /// 鞋型
        /// </summary>
        [Key]
        [StringLength(15)]
        public string Style_No { get; set; }
        /// <summary>
        ///         /// &#24037;&#20855;&#39006;&#21029;
        /// </summary>
        [Key]
        [StringLength(3)]
        public string Tool_Class { get; set; }
        /// <summary>
        ///         /// &#24037;&#20855;&#20195;&#34399;
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Tool_No { get; set; }
        /// <summary>
        ///         /// &#24207;&#34399;(1-30)
        /// </summary>
        [Key]
        public short Seq { get; set; }
        /// <summary>
        ///         /// &#38795;&#22411;&#23610;&#23544;
        /// </summary>
        [StringLength(4)]
        public string Style_Size { get; set; }
        /// <summary>
        ///         /// &#24037;&#20855;&#23610;&#23544;
        /// </summary>
        [StringLength(4)]
        public string Tool_Size { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(6)]
        public string HP_User { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#26085;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? HP_Date { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(50)]
        public string Update_By { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}