// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_Squad_Time
    {
        [Required]
        [StringLength(10)]
        public string Factory_ID { get; set; }
        [Required]
        [StringLength(3)]
        public string Dept_ID { get; set; }
        [Column(TypeName = "date")]
        public DateTime Duty_Date { get; set; }
        [StringLength(1)]
        public string Squad { get; set; }
        [StringLength(4)]
        public string Start_Time { get; set; }
        [StringLength(4)]
        public string End_Time { get; set; }
        public int? Total_Work_Hours { get; set; }
    }
}