// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class HP_ie27_1
    {
        [Key]
        [StringLength(1)]
        public string manuf { get; set; }
        [Key]
        [StringLength(15)]
        public string manno { get; set; }
        [Key]
        [StringLength(3)]
        public string seq { get; set; }
        [Column(TypeName = "date")]
        public DateTime? etd { get; set; }
        [StringLength(15)]
        public string style { get; set; }
        [StringLength(40)]
        public string styna { get; set; }
        [StringLength(10)]
        public string scolna { get; set; }
        [StringLength(1)]
        public string kind { get; set; }
        [Required]
        [StringLength(3)]
        public string teamno { get; set; }
        [Column(TypeName = "decimal(3, 0)")]
        public decimal rate { get; set; }
        public short times { get; set; }
        [Column(TypeName = "decimal(4, 0)")]
        public decimal std { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal totqty { get; set; }
        [Column(TypeName = "date")]
        public DateTime as_bdate { get; set; }
        [Required]
        [StringLength(4)]
        public string as_btime { get; set; }
        [Column(TypeName = "date")]
        public DateTime as_edate { get; set; }
        [Required]
        [StringLength(4)]
        public string as_etime { get; set; }
        [Column(TypeName = "date")]
        public DateTime stfi_bdate { get; set; }
        [Required]
        [StringLength(4)]
        public string stfi_btime { get; set; }
        [Column(TypeName = "date")]
        public DateTime stfi_edate { get; set; }
        [Required]
        [StringLength(4)]
        public string stfi_etime { get; set; }
        [Column(TypeName = "date")]
        public DateTime sti_bdate { get; set; }
        [Required]
        [StringLength(4)]
        public string sti_btime { get; set; }
        [Column(TypeName = "date")]
        public DateTime sti_edate { get; set; }
        [Required]
        [StringLength(4)]
        public string sti_etime { get; set; }
        [Column(TypeName = "date")]
        public DateTime cut_bdate { get; set; }
        [Required]
        [StringLength(4)]
        public string cut_btime { get; set; }
        [Column(TypeName = "date")]
        public DateTime cut_edate { get; set; }
        [Required]
        [StringLength(4)]
        public string cut_etime { get; set; }
        [Required]
        [StringLength(6)]
        public string upusr { get; set; }
        [Column(TypeName = "date")]
        public DateTime upday { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
    }
}