// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class HP_ie32t
    {
        [Key]
        [StringLength(1)]
        public string manuf { get; set; }
        [Key]
        [StringLength(15)]
        public string manno { get; set; }
        [Key]
        [StringLength(3)]
        public string seq { get; set; }
        [Key]
        [StringLength(4)]
        public string part { get; set; }
        [Key]
        [StringLength(20)]
        public string apart { get; set; }
        [Key]
        [StringLength(5)]
        public string code { get; set; }
        [Key]
        [StringLength(10)]
        public string itnbr { get; set; }
        [Key]
        [StringLength(4)]
        public string size { get; set; }
        [StringLength(4)]
        public string tsize { get; set; }
        [Column(TypeName = "decimal(12, 5)")]
        public decimal qty { get; set; }
        [Column(TypeName = "decimal(12, 5)")]
        public decimal oqty { get; set; }
        [Column(TypeName = "decimal(12, 5)")]
        public decimal pqty { get; set; }
        [Column(TypeName = "decimal(12, 5)")]
        public decimal sqty { get; set; }
        [Required]
        [StringLength(4)]
        public string vendno { get; set; }
        [Required]
        [StringLength(1)]
        public string workshop { get; set; }
        [Required]
        [StringLength(6)]
        public string upusr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime upday { get; set; }
        [StringLength(10)]
        public string workno { get; set; }
        [StringLength(4)]
        public string center { get; set; }
        [StringLength(1)]
        public string flag { get; set; }
        [StringLength(10)]
        public string trno { get; set; }
        [StringLength(1)]
        public string tr_kind { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
    }
}