// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class HP_ie34_log
    {
        [Key]
        [StringLength(1)]
        public string manuf { get; set; }
        [Key]
        [StringLength(1)]
        public string kind { get; set; }
        [StringLength(15)]
        public string manno { get; set; }
        [StringLength(3)]
        public string seq { get; set; }
        [Key]
        [StringLength(10)]
        public string trno { get; set; }
        [StringLength(1)]
        public string stat { get; set; }
        public int? pcount { get; set; }
        [StringLength(6)]
        public string upusr { get; set; }
        [Column(TypeName = "date")]
        public DateTime? upday { get; set; }
        public TimeSpan? uptime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
    }
}