// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class HP_j02
    {
        [Key]
        public int codk { get; set; }
        [Key]
        [StringLength(4)]
        public string code { get; set; }
        [StringLength(40)]
        public string codsc { get; set; }
        [StringLength(50)]
        public string codmk { get; set; }
        [StringLength(5)]
        public string mark { get; set; }
        [StringLength(6)]
        public string upusr { get; set; }
        [Column(TypeName = "date")]
        public DateTime? upday { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDT { get; set; }
    }
}