// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class HP_n47_e
    {
        [Key]
        [StringLength(1)]
        public string manuf { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime exec_date { get; set; }
        [StringLength(3)]
        public string teamno { get; set; }
        [StringLength(20)]
        public string teamcna { get; set; }
        [Key]
        [StringLength(15)]
        public string manno { get; set; }
        [Key]
        [StringLength(3)]
        public string seq { get; set; }
        [StringLength(40)]
        public string styna { get; set; }
        [StringLength(15)]
        public string style { get; set; }
        [StringLength(70)]
        public string custyle { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal plan_qty { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal bat_plan_qty { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal fgin_qty { get; set; }
        [Column(TypeName = "date")]
        public DateTime last_fgin_date { get; set; }
        [Required]
        [StringLength(1)]
        public string is_complete { get; set; }
        [Column(TypeName = "decimal(6, 0)")]
        public decimal stc_prod_qty { get; set; }
        [Column(TypeName = "decimal(6, 0)")]
        public decimal stc_balance { get; set; }
        [Required]
        [StringLength(1)]
        public string stc_is_complete { get; set; }
        [Column(TypeName = "date")]
        public DateTime? stc_last_date { get; set; }
        [Required]
        [StringLength(1)]
        public string stc_need_replenish { get; set; }
        [Column(TypeName = "decimal(6, 0)")]
        public decimal stf_prod_qty { get; set; }
        [Column(TypeName = "decimal(6, 0)")]
        public decimal stf_balance { get; set; }
        [Required]
        [StringLength(1)]
        public string stf_is_complete { get; set; }
        [Column(TypeName = "date")]
        public DateTime? stf_last_date { get; set; }
        [Required]
        [StringLength(1)]
        public string stf_need_replenish { get; set; }
        [Required]
        [StringLength(6)]
        public string upusr { get; set; }
        [Column(TypeName = "date")]
        public DateTime upday { get; set; }
        public TimeSpan uptime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDT { get; set; }
    }
}