// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Dispatch_Area
    {
        [Key]
        [StringLength(4)]
        public string Area_ID { get; set; }
        [Required]
        [StringLength(25)]
        public string Area_Name { get; set; }
        [Column(TypeName = "text")]
        public string Area_Description { get; set; }
        [Required]
        [StringLength(10)]
        public string isActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Insert_At { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_At { get; set; }
    }
}