// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Replenish_Collect
    {
        [StringLength(10)]
        public string Factory_ID { get; set; }
        public int SeqOfDate { get; set; }
        [Required]
        [StringLength(20)]
        public string Collect_No { get; set; }
        [Column(TypeName = "date")]
        public DateTime Collect_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Collect_At { get; set; }
        [Required]
        [StringLength(10)]
        public string Collect_By { get; set; }
        [Key]
        [StringLength(20)]
        public string Material_Sheet_No { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? MatlNoHave_ReadyQty { get; set; }
        public bool isDownloaded { get; set; }
    }
}