// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Replenish_Cancel_Code
    {
        [Key]
        [StringLength(3)]
        public string Code { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        public bool isActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Insert_At { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_At { get; set; }
    }
}