// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Cmpt_T1T3_351Receipt
    {
        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime T1_Receipt_Date { get; set; }
        [Required]
        [StringLength(15)]
        public string T3_Shipment_No { get; set; }
        [Required]
        [StringLength(20)]
        public string T1_Purchase_No { get; set; }
        [Required]
        [StringLength(15)]
        public string MO_No { get; set; }
        [Required]
        [StringLength(3)]
        public string MO_Batch { get; set; }
        [Required]
        [StringLength(4)]
        public string Supplier_No { get; set; }
        [Required]
        [StringLength(9)]
        public string Process_Material_No { get; set; }
        [Required]
        [StringLength(5)]
        public string Process_No { get; set; }
        [Required]
        [StringLength(4)]
        public string Internal_Part_No { get; set; }
        [Required]
        [StringLength(4)]
        public string MO_Size { get; set; }
        public int QC_Pass_Qty { get; set; }
        public int Receipt_Qty { get; set; }
        /// <summary>
        ///         /// 1. &#27491;&#25209; ; 4. &#35036;&#26009;
        /// </summary>
        [Required]
        [StringLength(1)]
        public string Purchase_Kind { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
        [StringLength(4)]
        public string Kind { get; set; }
    }
}