// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Cmpt_Workstation
    {
        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime Effective_Date { get; set; }
        [Required]
        [StringLength(15)]
        public string Workstation_Code { get; set; }
        [Required]
        [StringLength(50)]
        public string Workstation_Desc { get; set; }
        [Required]
        [StringLength(10)]
        public string Factory_Code { get; set; }
        [Required]
        [StringLength(10)]
        public string TreatmentDept_Code { get; set; }
        [Required]
        [StringLength(10)]
        public string Build_Code { get; set; }
        [Required]
        [StringLength(10)]
        public string TreatmentGroup_Code { get; set; }
        [Required]
        [StringLength(10)]
        public string WorkstationType_Code { get; set; }
        [Required]
        [StringLength(5)]
        public string Workstation_Seq { get; set; }
        [StringLength(6)]
        public string Asset_No { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Insert_At { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_At { get; set; }
    }
}