// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#26448;&#26009;&#28310;&#20633;&#31995;&#32113;&#8212;&#35036;&#26009;&#24409;&#32317;
    /// </summary>
    public partial class MPS_Material_Replenish_Collect
    {
        /// <summary>
        ///         /// 廠別
        /// </summary>
        [StringLength(10)]
        public string Factory_ID { get; set; }
        /// <summary>
        ///         /// &#24409;&#32317;&#34399;
        /// </summary>
        [Key]
        [StringLength(20)]
        public string Collect_No { get; set; }
        /// <summary>
        ///         /// &#30332;&#26009;&#21934;&#34399;
        /// </summary>
        [Key]
        [StringLength(20)]
        public string Material_Sheet_No { get; set; }
        /// <summary>
        ///         /// &#24409;&#32317;&#26085;&#26399;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? Collect_Date { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(10)]
        public string HP_User { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#26085;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? HP_Day { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "time(0)")]
        public TimeSpan? HP_Time { get; set; }
        /// <summary>
        ///         /// biztalk&#36681;&#20837;&#26041;&#24335;
        /// </summary>
        [StringLength(1)]
        public string Biz_Tflag { get; set; }
        /// <summary>
        ///         /// &#29376;&#24907;
        /// </summary>
        [StringLength(1)]
        public string Status { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(50)]
        public string Update_By { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}