// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Cmpt_FBSection_TotQty
    {
        [Key]
        [StringLength(15)]
        public string MO_No { get; set; }
        [Key]
        [StringLength(3)]
        public string MO_Batch { get; set; }
        [StringLength(1)]
        public string Section { get; set; }
        [Key]
        [StringLength(5)]
        public string Process_No { get; set; }
        [StringLength(4)]
        public string Supplier_No { get; set; }
        [Key]
        [StringLength(4)]
        public string Internal_Part_No { get; set; }
        [Key]
        [StringLength(4)]
        public string MO_Size { get; set; }
        [Key]
        [StringLength(4)]
        public string Kind { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal Total_Qty { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
    }
}