// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#26448;&#26009;&#28310;&#20633;&#31995;&#32113;&#65293;&#35036;&#26009;
    /// </summary>
    public partial class MPS_Material_Replenish
    {
        /// <summary>
        ///         /// 廠別
        /// </summary>
        [StringLength(10)]
        public string Factory_ID { get; set; }
        /// <summary>
        ///         /// &#38283;&#35036;&#21934;&#34399;
        /// </summary>
        [Key]
        [StringLength(20)]
        public string Replenish_No { get; set; }
        /// <summary>
        ///         /// &#38283;&#35036;&#26085;&#26399;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? Replenish_Date { get; set; }
        /// <summary>
        ///         /// &#24235;&#21029;
        /// </summary>
        [StringLength(5)]
        public string Warehouse_ID { get; set; }
        /// <summary>
        ///         /// &#37096;&#20301;
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Part { get; set; }
        /// <summary>
        ///         /// &#26448;&#26009;
        /// </summary>
        [Key]
        [StringLength(20)]
        public string Material_ID { get; set; }
        /// <summary>
        ///         /// &#26448;&#26009;&#21312;&#20998;
        /// </summary>
        [StringLength(1)]
        public string Material_Type { get; set; }
        /// <summary>
        ///         /// &#20225;&#21123;&#21934;&#34399;
        /// </summary>
        [Key]
        [StringLength(20)]
        public string MO_No { get; set; }
        /// <summary>
        ///         /// &#23610;&#23544;
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Size { get; set; }
        /// <summary>
        ///         /// &#21934;&#20301;&#29992;&#37327;
        /// </summary>
        [Column(TypeName = "decimal(8, 5)")]
        public decimal? Unit_Qty { get; set; }
        /// <summary>
        ///         /// &#38617;&#25976;
        /// </summary>
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? Pairs { get; set; }
        /// <summary>
        ///         /// &#25976;&#37327;
        /// </summary>
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? Qty { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;
        /// </summary>
        [StringLength(10)]
        public string Dept_ID { get; set; }
        /// <summary>
        ///         /// &#21407;&#22240;
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Cause { get; set; }
        /// <summary>
        ///         /// &#35036;&#38795;&#27425;&#25976;
        /// </summary>
        [Key]
        public short Replenish_Count { get; set; }
        /// <summary>
        ///         /// &#20633;&#35387;
        /// </summary>
        [StringLength(1)]
        public string Mark { get; set; }
        /// <summary>
        ///         /// &#30332;&#26009;&#21934;&#34399;
        /// </summary>
        [StringLength(20)]
        public string Material_Sheet_No { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(10)]
        public string HP_User { get; set; }
        /// <summary>
        ///         /// HP&#30064;&#21205;&#26085;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? HP_Date { get; set; }
        /// <summary>
        ///         /// biztalk&#36681;&#20837;&#26041;&#24335;
        /// </summary>
        [StringLength(1)]
        public string Biz_Tflag { get; set; }
        /// <summary>
        ///         /// &#29376;&#24907;
        /// </summary>
        [StringLength(1)]
        public string Status { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(50)]
        public string Update_By { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Supp_Schedule_Date { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Supp_Sche_SwitchDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_SuppSchedule_At { get; set; }
    }
}