// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Cmpt_Transaction_FBBy
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(20)]
        public string Transaction_No { get; set; }
        [Required]
        [StringLength(15)]
        public string MO_No { get; set; }
        [Required]
        [StringLength(3)]
        public string MO_Batch { get; set; }
        [Required]
        [StringLength(2)]
        public string MO_Sequence { get; set; }
        [Required]
        [StringLength(5)]
        public string Process_No { get; set; }
        [Required]
        [StringLength(4)]
        public string Internal_Part_No { get; set; }
        [Required]
        [StringLength(9)]
        public string Process_Material_No { get; set; }
        [Required]
        [StringLength(2)]
        public string Feedback_Stage { get; set; }
        [Required]
        [StringLength(15)]
        public string Feedback_By { get; set; }
        [StringLength(20)]
        public string Refer_Transaction_No { get; set; }
        [Required]
        [StringLength(4)]
        public string MO_Size { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal? Output_To_Refer_Transaction { get; set; }
    }
}