// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Replenish_Check_Record
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(1)]
        public string manuf { get; set; }
        [Column(TypeName = "date")]
        public DateTime exec_date { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [Required]
        [StringLength(3)]
        public string ProdProcess { get; set; }
        public short Click_Check_Sort { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CheckDT { get; set; }
        [Required]
        [StringLength(10)]
        public string CheckBy { get; set; }
    }
}