// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Cmpt_Process_Workstation
    {
        [Key]
        public Guid ID { get; set; }
        [Required]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        [Required]
        [StringLength(5)]
        public string Process_No { get; set; }
        [Required]
        [StringLength(20)]
        public string Workstation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Insert_At { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_At { get; set; }
    }
}