// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Basic_LastFormNo_Record
    {
        [Key]
        [StringLength(20)]
        public string Form_Kind { get; set; }
        [Key]
        [StringLength(30)]
        public string Form_No_Factor { get; set; }
        [Key]
        [StringLength(50)]
        public string Form_No_Factor_Value { get; set; }
        public int Form_Last_No { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
    }
}