// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Replenish_PB3A4
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(20)]
        public string Replenish_No { get; set; }
        [Required]
        [StringLength(20)]
        public string Material_Sheet_No { get; set; }
        [Required]
        [StringLength(20)]
        public string Replenish_Collect_No { get; set; }
        [Required]
        [StringLength(20)]
        public string MO_No { get; set; }
        [Required]
        [StringLength(20)]
        public string Purch_No { get; set; }
        [Required]
        [StringLength(20)]
        public string Main_Material_ID { get; set; }
        [Required]
        [StringLength(20)]
        public string Sub_Material_ID { get; set; }
        [Column(TypeName = "date")]
        public DateTime T2_Confirm_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
    }
}