// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Basic_Code_List
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(10)]
        public string Code_Kind { get; set; }
        [Required]
        [StringLength(10)]
        public string Code { get; set; }
        [Required]
        [StringLength(250)]
        public string ENG_Description { get; set; }
        [StringLength(250)]
        public string CHT_Description { get; set; }
        [StringLength(250)]
        public string LCL_Description { get; set; }
        public int? Seq_of_Code { get; set; }
        public bool isValid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Valid_At { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Invalid_At { get; set; }
    }
}