// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Cmpt_Transaction_Summary
    {
        [Key]
        [StringLength(20)]
        public string Transaction_No { get; set; }
        [Column(TypeName = "date")]
        public DateTime Transaction_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Transaction_At { get; set; }
        [Required]
        [StringLength(10)]
        public string Transaction_By { get; set; }
        [Required]
        [StringLength(1)]
        public string Processing_Last_Status { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Processing_Finish_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Processing_Finish_At { get; set; }
        [StringLength(10)]
        public string Processing_Finish_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal? Working_Hours { get; set; }
    }
}