// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Replenish_Status_Detail
    {
        [Key]
        [StringLength(20)]
        public string Material_Sheet_No { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? MatlNoHave_At { get; set; }
        [StringLength(10)]
        public string MatlNoHave_By { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? MatlNoHave_ReadyQty { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DownloadCSV_At { get; set; }
        [StringLength(10)]
        public string DownloadCSV_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Ready_At { get; set; }
        [StringLength(10)]
        public string Ready_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SReady_At { get; set; }
        [StringLength(10)]
        public string SReady_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Dispatch_At { get; set; }
        [StringLength(10)]
        public string Dispatch_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ProdRequestDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Cancel_At { get; set; }
        [StringLength(3)]
        public string Cancel_Code { get; set; }
        [StringLength(10)]
        public string Cancel_By { get; set; }
    }
}