// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Basic_UserAutho
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Autho_Kind { get; set; }
        [Required]
        [StringLength(10)]
        public string Account { get; set; }
        [Required]
        [StringLength(100)]
        public string Autho_Value { get; set; }
    }
}