// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Cmpt_Shift_Quantity
    {
        [Key]
        [StringLength(20)]
        public string Shift_No { get; set; }
        [Column(TypeName = "date")]
        public DateTime Shift_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Shift_At { get; set; }
        [Required]
        [StringLength(10)]
        public string Shift_By { get; set; }
        [Key]
        [StringLength(15)]
        public string MO_No { get; set; }
        [Key]
        [StringLength(3)]
        public string MO_Batch { get; set; }
        [Key]
        [StringLength(5)]
        public string Process_No { get; set; }
        [Key]
        [StringLength(4)]
        public string Internal_Part_No { get; set; }
        [StringLength(20)]
        public string External_Part_No { get; set; }
        [Required]
        [StringLength(9)]
        public string Process_Material_No { get; set; }
        [Key]
        [StringLength(4)]
        public string Kind { get; set; }
        [Key]
        [StringLength(4)]
        public string MO_Size { get; set; }
        [StringLength(4)]
        public string Tooling_Size { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal Shift_Qty { get; set; }
    }
}