// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class MPS_Replenish_Claim_Detail
    {
        [StringLength(10)]
        public string Factory_ID { get; set; }
        [Key]
        [StringLength(20)]
        public string Material_Sheet_No { get; set; }
        public int? SeqOfDate { get; set; }
        [StringLength(20)]
        public string Collect_No { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Collect_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CollectAt { get; set; }
        [StringLength(10)]
        public string CollectBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DownloadedAt { get; set; }
    }
}