// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TAuthoList
    {
        public TAuthoList()
        {
            TMenu = new HashSet<TMenu>();
        }

        [Key]
        public int ID { get; set; }
        [StringLength(50)]
        public string AuthName { get; set; }
        public int AuthIndex { get; set; }

        [InverseProperty("Autho")]
        public virtual ICollection<TMenu> TMenu { get; set; }
    }
}