// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TAuthoPickupForm
    {
        [Key]
        [StringLength(10)]
        public string account { get; set; }
        [Key]
        [StringLength(2)]
        public string Kind { get; set; }
    }
}