// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TAutho
    {
        [Key]
        [StringLength(10)]
        public string account { get; set; }
        [Required]
        [StringLength(6)]
        public string empno { get; set; }
        [Required]
        [StringLength(1024)]
        public string Autho { get; set; }
        [StringLength(50)]
        public string AuthDSS { get; set; }
        [Required]
        [StringLength(100)]
        public string DefaultMenu { get; set; }
        [StringLength(3)]
        public string Cellno { get; set; }
        [StringLength(4)]
        public string Default_DispatchArea_ID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Last_Login_At { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? insert_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? update_at { get; set; }
    }
}