// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TCentralUpload
    {
        [Key]
        [StringLength(15)]
        public string PO { get; set; }
        [Key]
        [StringLength(4)]
        public string Batch { get; set; }
        [Key]
        [StringLength(20)]
        public string Seq { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal TotQty { get; set; }
        [StringLength(5)]
        public string Teamno { get; set; }
        [StringLength(5)]
        public string TimeStart { get; set; }
        [StringLength(5)]
        public string TimeEnd { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateAt { get; set; }
    }
}