// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TCentralKind
    {
        [Key]
        public int Id { get; set; }
        [StringLength(20)]
        public string Kind { get; set; }
        public bool IsActive { get; set; }
    }
}