// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#21462;&#26009;&#21934;&#36913;&#36681;&#37096;&#20301;&#26448;&#26009;
    /// </summary>
    public partial class TCMS_IEPKList
    {
        /// <summary>
        ///         /// 廠別
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Factory_ID { get; set; }
        /// <summary>
        ///         /// &#39006;&#21029;
        /// </summary>
        [Key]
        [StringLength(1)]
        public string Kind { get; set; }
        /// <summary>
        ///         /// &#21462;&#26009;&#21934;&#34399;
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Trno { get; set; }
        /// <summary>
        ///         /// &#20225;&#21123;&#21934;&#34399;
        /// </summary>
        [StringLength(15)]
        public string MO_No { get; set; }
        /// <summary>
        ///         /// &#25209;&#27425;
        /// </summary>
        [StringLength(3)]
        public string MO_Seq { get; set; }
        /// <summary>
        ///         /// &#36913;&#36681;&#34399;
        /// </summary>
        [Key]
        [StringLength(21)]
        public string Cycle_No { get; set; }
        /// <summary>
        ///         /// &#37096;&#20301;
        /// </summary>
        [Key]
        [StringLength(4)]
        public string Part { get; set; }
        /// <summary>
        ///         /// &#26009;&#34399;
        /// </summary>
        [Key]
        [StringLength(10)]
        public string Item_NBR { get; set; }
        /// <summary>
        ///         /// &#23610;&#23544;
        /// </summary>
        [Key]
        [StringLength(4)]
        public string Size { get; set; }
        /// <summary>
        ///         /// &#25351;&#23450;&#30340;&#21462;&#26009;&#37327;
        /// </summary>
        [Column(TypeName = "decimal(12, 5)")]
        public decimal? O_Qty { get; set; }
        /// <summary>
        ///         /// &#25351;&#23450;&#30340;&#20225;&#21123;&#37327;
        /// </summary>
        [Column(TypeName = "decimal(12, 5)")]
        public decimal? P_Qty { get; set; }
        /// <summary>
        ///         /// &#24288;&#21830;
        /// </summary>
        [StringLength(10)]
        public string Vender_No { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(50)]
        public string Update_By { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}