// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TCMS_IEPKList_Log
    {
        [Key]
        [StringLength(10)]
        public string Factory_ID { get; set; }
        [Key]
        [StringLength(1)]
        public string Kind { get; set; }
        [Key]
        [StringLength(10)]
        public string Trno { get; set; }
        [StringLength(15)]
        public string MO_No { get; set; }
        [StringLength(3)]
        public string MO_Seq { get; set; }
        [Key]
        [StringLength(21)]
        public string Cycle_No { get; set; }
        [Key]
        [StringLength(4)]
        public string Part { get; set; }
        [Key]
        [StringLength(10)]
        public string Item_NBR { get; set; }
        [Key]
        [StringLength(4)]
        public string Size { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal? O_Qty { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal? P_Qty { get; set; }
        [StringLength(10)]
        public string Vender_No { get; set; }
        [StringLength(50)]
        public string Update_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}