// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class THPie83
    {
        [Required]
        [StringLength(25)]
        public string grpno { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertDT { get; set; }
        [Key]
        [StringLength(20)]
        public string manno { get; set; }
        [Key]
        [StringLength(1)]
        public string manuf { get; set; }
        [Required]
        [StringLength(6)]
        public string scolna { get; set; }
        [Key]
        [StringLength(3)]
        public string seq { get; set; }
        [Required]
        [StringLength(3)]
        public string teamno { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal totqty { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime upday { get; set; }
        [Required]
        [StringLength(6)]
        public string upusr { get; set; }
    }
}