// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class THPi14a
    {
        [Key]
        [StringLength(1)]
        public string manuf { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime ymd { get; set; }
        [Key]
        [StringLength(3)]
        public string dept { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal goal { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal goalhr { get; set; }
        [Required]
        [StringLength(6)]
        public string upusr { get; set; }
        [Column(TypeName = "date")]
        public DateTime upday { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime InsertDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDT { get; set; }
    }
}