// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class THPn15_4
    {
        [Key]
        [StringLength(1)]
        public string manuf { get; set; }
        [Key]
        [StringLength(3)]
        public string lean { get; set; }
        [Key]
        public short seq { get; set; }
        [Required]
        [StringLength(3)]
        public string dept { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime aday { get; set; }
        [Required]
        [StringLength(6)]
        public string upusr { get; set; }
        [Column(TypeName = "date")]
        public DateTime upday { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdateDT { get; set; }
    }
}