// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TIE25
    {
        [Key]
        [StringLength(2)]
        public string Factory { get; set; }
        [Key]
        [StringLength(10)]
        public string Squad { get; set; }
        [Key]
        [StringLength(3)]
        public string Teamno { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime DateEff { get; set; }
    }
}