// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class Tie29
    {
        [Key]
        [StringLength(1)]
        public string manuf { get; set; }
        [Key]
        [StringLength(15)]
        public string manno { get; set; }
        [Key]
        [StringLength(3)]
        public string seq { get; set; }
        [Key]
        [StringLength(21)]
        public string cyno { get; set; }
        public short cycle { get; set; }
        public short times { get; set; }
        [Required]
        [StringLength(1)]
        public string day_sch { get; set; }
        [Required]
        [StringLength(1)]
        public string get_no { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal totqty { get; set; }
        [Column(TypeName = "date")]
        public DateTime as_bdate { get; set; }
        [Required]
        [StringLength(4)]
        public string as_btime { get; set; }
        [Column(TypeName = "date")]
        public DateTime as_edate { get; set; }
        [Required]
        [StringLength(4)]
        public string as_etime { get; set; }
        [Column(TypeName = "date")]
        public DateTime stfi_bdate { get; set; }
        [Required]
        [StringLength(4)]
        public string stfi_btime { get; set; }
        [Column(TypeName = "date")]
        public DateTime stfi_edate { get; set; }
        [Required]
        [StringLength(4)]
        public string stfi_etime { get; set; }
        [Column(TypeName = "date")]
        public DateTime sti_bdate { get; set; }
        [Required]
        [StringLength(4)]
        public string sti_btime { get; set; }
        [Column(TypeName = "date")]
        public DateTime sti_edate { get; set; }
        [Required]
        [StringLength(4)]
        public string sti_etime { get; set; }
        [Column(TypeName = "date")]
        public DateTime cut_bdate { get; set; }
        [Required]
        [StringLength(4)]
        public string cut_btime { get; set; }
        [Column(TypeName = "date")]
        public DateTime cut_edate { get; set; }
        [Required]
        [StringLength(4)]
        public string cut_etime { get; set; }
        [Required]
        [StringLength(6)]
        public string upusr { get; set; }
        [Column(TypeName = "date")]
        public DateTime upday { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdateDT { get; set; }
    }
}