// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TIPAuthorization
    {
        [Key]
        [StringLength(15)]
        public string IP { get; set; }
        [StringLength(12)]
        public string AuthoIOP { get; set; }
        [StringLength(50)]
        public string Remark { get; set; }
    }
}