// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TMenu
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string MenuDisplay { get; set; }
        [StringLength(50)]
        public string MenuIcon { get; set; }
        public int MenuOrder { get; set; }
        [StringLength(15)]
        public string MenuParent { get; set; }
        [StringLength(255)]
        public string Path { get; set; }
        public int? AuthoID { get; set; }

        [ForeignKey(nameof(AuthoID))]
        [InverseProperty(nameof(TAuthoList.TMenu))]
        public virtual TAuthoList Autho { get; set; }
    }
}