// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TNotice
    {
        [Key]
        [StringLength(12)]
        public string NoticeID { get; set; }
        public int SeqOfDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime GenerateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime GenerateAt { get; set; }
        [Required]
        [StringLength(10)]
        public string GenerateBy { get; set; }
    }
}