// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TOrg
    {
        [Key]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        [Key]
        [StringLength(1)]
        public string PDC_ID { get; set; }
        [StringLength(20)]
        public string PDC_Name { get; set; }
        [Key]
        [StringLength(3)]
        public string Line_ID { get; set; }
        [StringLength(20)]
        public string Line_Name { get; set; }
        [Key]
        [StringLength(3)]
        public string Dept_ID { get; set; }
        [StringLength(10)]
        public string Building { get; set; }
        public int? Line_Seq { get; set; }
        public int? Status { get; set; }
        [StringLength(1)]
        public string Block { get; set; }
        [Required]
        [StringLength(1)]
        public string Dept_Kind { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
        [StringLength(16)]
        public string Updated_By { get; set; }
    }
}