// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TPartPrepareQtys
    {
        [Key]
        [StringLength(2)]
        public string kind { get; set; }
        [Key]
        [StringLength(10)]
        public string trno { get; set; }
        [Key]
        [StringLength(10)]
        public string itnbr { get; set; }
        [Key]
        [StringLength(4)]
        public string size { get; set; }
        [Column(TypeName = "decimal(15, 1)")]
        public decimal? PartPrepareBalance { get; set; }
        [Column(TypeName = "decimal(15, 1)")]
        public decimal? PartPrepareQty { get; set; }
        [Column(TypeName = "decimal(15, 1)")]
        public decimal? ProdCheckBalance { get; set; }
        [Column(TypeName = "decimal(15, 1)")]
        public decimal? ProdCheckQty { get; set; }
        [Column(TypeName = "date")]
        public DateTime? SuppBalScheUpdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
    }
}