// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TPartPrepareDates
    {
        [Key]
        [StringLength(2)]
        public string kind { get; set; }
        [Key]
        [StringLength(10)]
        public string trno { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PartPrepareDate { get; set; }
        [StringLength(1)]
        public string isHadPrepareBalance { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DispatchDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpireProdReceiveDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ActualProdReceiveDate { get; set; }
        [StringLength(1)]
        public string isHadProdReceiveBalance { get; set; }
        [StringLength(12)]
        public string WHNoticeNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? WHNoticeDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? SuppBalScheUpdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ProdClosingDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? InsertAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateAt { get; set; }
    }
}