// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TPickupFormKind
    {
        [Key]
        [StringLength(2)]
        public string Kind { get; set; }
        [Required]
        [StringLength(5)]
        public string Prefix { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(250)]
        public string LongName { get; set; }
        public int OrderNum { get; set; }
    }
}