// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TPickupFormStatus
    {
        [Key]
        [StringLength(10)]
        public string trno { get; set; }
        [Key]
        [StringLength(2)]
        public string kind { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? whchkstock_at { get; set; }
        [StringLength(10)]
        public string whchkstock_by { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? settingmatl_at { get; set; }
        [StringLength(10)]
        public string settingmatl_by { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prepare_at { get; set; }
        [StringLength(10)]
        public string prepare_by { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dispatch_at { get; set; }
        [StringLength(10)]
        public string dispatch_by { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? call_at { get; set; }
        [StringLength(10)]
        public string call_by { get; set; }
        [StringLength(10)]
        public string Dispatch_To { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prodcheck_at { get; set; }
        [StringLength(10)]
        public string prodcheck_by { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? closing_at { get; set; }
        [StringLength(10)]
        public string closing_by { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prepare_actualAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dispatch_actualAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? call_actualAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prodcheck_actualAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? closing_actualAt { get; set; }
    }
}