// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TPickupForm
    {
        [Key]
        [StringLength(10)]
        public string trno { get; set; }
        [Key]
        [StringLength(2)]
        public string kind { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal seqqty { get; set; }
        public int seqfrom { get; set; }
        public int seqto { get; set; }
        [Column(TypeName = "date")]
        public DateTime? create_at { get; set; }
        [Column(TypeName = "date")]
        public DateTime? print_at { get; set; }
        [Column(TypeName = "date")]
        public DateTime? update_at { get; set; }
    }
}