// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class TSettings
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(100)]
        public string key { get; set; }
        [Required]
        [Column(TypeName = "ntext")]
        public string value { get; set; }
    }
}