// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VCentralize
    {
        [StringLength(5)]
        public string Teamno { get; set; }
        [Required]
        [StringLength(15)]
        public string PO { get; set; }
        [Required]
        [StringLength(4)]
        public string Batch { get; set; }
        [Required]
        [StringLength(20)]
        public string Seq { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal TotQty { get; set; }
        [Required]
        [StringLength(5)]
        public string TimeStart { get; set; }
        [Required]
        [StringLength(5)]
        public string TimeEnd { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateAt { get; set; }
        public int Kind { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? PrepareQty { get; set; }
        [StringLength(10)]
        public string PrepareBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PrepareAt { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? CallQty { get; set; }
        [StringLength(10)]
        public string CallBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CallAt { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? DispatchQty { get; set; }
        [StringLength(10)]
        public string DispatchBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DispatchAt { get; set; }
    }
}