// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vMergedPOPlan
    {
        [Required]
        [StringLength(1)]
        public string manuf { get; set; }
        [Required]
        [StringLength(25)]
        public string grpno { get; set; }
        [Required]
        [StringLength(3)]
        public string MergedTeamno { get; set; }
        [Required]
        [StringLength(20)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal totqty { get; set; }
        [Required]
        [StringLength(3)]
        public string PlanTeamno { get; set; }
        [Column(TypeName = "date")]
        public DateTime? as_bdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? as_edate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? cut_bdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? cut_edate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prepare_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? call_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dispatch_at { get; set; }
        [Required]
        [StringLength(10)]
        public string trno { get; set; }
        [Required]
        [StringLength(2)]
        public string kind { get; set; }
    }
}