// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VOrderDeptLastProductionDate
    {
        [Required]
        [StringLength(15)]
        public string OrderNo { get; set; }
        [StringLength(3)]
        public string Dept_ID { get; set; }
        [StringLength(3)]
        public string PS_ID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastProdDate { get; set; }
    }
}