// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VPartialPreparationDet
    {
        [Required]
        [StringLength(2)]
        public string kind { get; set; }
        [Required]
        [StringLength(10)]
        public string trno { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [Required]
        [StringLength(3)]
        public string teamno { get; set; }
        [Required]
        [StringLength(10)]
        public string itnbr { get; set; }
        [Required]
        [StringLength(4)]
        public string size { get; set; }
        [Column(TypeName = "decimal(38, 5)")]
        public decimal? PlanQty { get; set; }
        [Column(TypeName = "decimal(15, 1)")]
        public decimal? PartPrepareBalance { get; set; }
        [Column(TypeName = "decimal(15, 1)")]
        public decimal? PartPrepareQty { get; set; }
        [Column(TypeName = "decimal(15, 1)")]
        public decimal? ProdCheckBalance { get; set; }
        [Column(TypeName = "decimal(15, 1)")]
        public decimal? ProdCheckQty { get; set; }
        [Column(TypeName = "date")]
        public DateTime? SuppBalScheUpdateSize { get; set; }
        [StringLength(12)]
        public string WHNoticeNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? WHNoticeDate { get; set; }
        [StringLength(10)]
        public string Vender_No { get; set; }
        [Column(TypeName = "date")]
        public DateTime? as_bdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PartPrepareDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? call_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DispatchDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpireProdReceiveDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ActualProdReceiveDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? SuppBalScheUpdatePUF { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ProdClosingDate { get; set; }
    }
}