// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vPOnMERGErelation
    {
        [Required]
        [StringLength(9)]
        public string Category { get; set; }
        [StringLength(25)]
        public string grpno { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [StringLength(40)]
        public string styna { get; set; }
        [StringLength(15)]
        public string style { get; set; }
        [StringLength(10)]
        public string scolna { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal batchqty { get; set; }
        [Required]
        [StringLength(3)]
        public string teamno { get; set; }
        [Column(TypeName = "date")]
        public DateTime? as_bdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? as_edate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? cut_bdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? cut_edate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? stfi_bdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? stfi_edate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? sti_bdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? sti_edate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? trt_bdate { get; set; }
    }
}