// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vPUFDetailStatus
    {
        [Required]
        [StringLength(9)]
        public string Category { get; set; }
        [StringLength(25)]
        public string PUFNo { get; set; }
        [Required]
        [StringLength(10)]
        public string Trno { get; set; }
        [Required]
        [StringLength(2)]
        public string Kind { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal seqqty { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? whchkstock_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? settingmatl_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prepare_at { get; set; }
        [StringLength(1)]
        public string isHadPrepareBalance { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? call_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dispatch_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpireProdReceiveDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prodcheck_at { get; set; }
        [StringLength(1)]
        public string isHadProdReceiveBalance { get; set; }
        [StringLength(12)]
        public string WHNoticeNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? WHNoticeDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? closing_at { get; set; }
    }
}