// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vPUFnMERGErelation
    {
        [Required]
        [StringLength(9)]
        public string Category { get; set; }
        [StringLength(25)]
        public string PUFNo { get; set; }
        [Required]
        [StringLength(10)]
        public string Trno { get; set; }
        [Required]
        [StringLength(2)]
        public string Kind { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal seqqty { get; set; }
    }
}