// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vPUFCycleDetail
    {
        [Required]
        [StringLength(10)]
        public string trno { get; set; }
        [Required]
        [StringLength(2)]
        public string kind { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        public short cycle { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal totqty { get; set; }
        [Column(TypeName = "date")]
        public DateTime as_bdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime stfi_bdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime sti_bdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime cut_bdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? prepare_at { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dispatch_at { get; set; }
        [Required]
        [StringLength(3)]
        public string teamno { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal prepareqty { get; set; }
        [Column(TypeName = "decimal(15, 5)")]
        public decimal dispatchqty { get; set; }
    }
}