// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vReplenishCheckSummary
    {
        [Column(TypeName = "date")]
        public DateTime exec_date { get; set; }
        [Required]
        [StringLength(1)]
        public string manuf { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [StringLength(40)]
        public string styna { get; set; }
        [StringLength(70)]
        public string custyle { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal plan_qty { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? AccuFGIN { get; set; }
        [Column(TypeName = "date")]
        public DateTime? last_fgin_date { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? FGIN_Balance { get; set; }
        [Column(TypeName = "decimal(38, 0)")]
        public decimal? CTL_Balance { get; set; }
        [Column(TypeName = "decimal(38, 0)")]
        public decimal? STC_Balance { get; set; }
        [Column(TypeName = "decimal(38, 0)")]
        public decimal? STF_Balance { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastCheckCTL { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastCheckSTC { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastCheckASL { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastCheckSTF { get; set; }
    }
}