// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vReplenish_Collect_Detail
    {
        [Required]
        [StringLength(20)]
        public string Collect_No { get; set; }
        [Column(TypeName = "date")]
        public DateTime Collect_Date { get; set; }
        [Required]
        [StringLength(20)]
        public string Replenish_No { get; set; }
        [StringLength(20)]
        public string Material_Sheet_No { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Replenish_Date { get; set; }
        public short Replenish_Count { get; set; }
        [Required]
        [StringLength(20)]
        public string MO_No { get; set; }
        [Required]
        [StringLength(10)]
        public string Part { get; set; }
        [Required]
        [StringLength(20)]
        public string Material_ID { get; set; }
        [Required]
        [StringLength(10)]
        public string Size { get; set; }
        [Required]
        [StringLength(10)]
        public string Cause { get; set; }
        [Column(TypeName = "decimal(9, 2)")]
        public decimal? Qty { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Supp_Schedule_Date { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Supp_Sche_SwitchDate { get; set; }
    }
}