// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vReplenish_SizePrint
    {
        [StringLength(10)]
        public string Factory_ID { get; set; }
        [Required]
        [StringLength(20)]
        public string Replenish_No { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Replenish_Date { get; set; }
        [StringLength(20)]
        public string Material_Sheet_No { get; set; }
        [Required]
        [StringLength(20)]
        public string MO_No { get; set; }
        [Required]
        [StringLength(20)]
        public string Material_ID { get; set; }
        [StringLength(240)]
        public string Material_E_Name { get; set; }
        [StringLength(1)]
        public string Material_Type { get; set; }
        [StringLength(1)]
        public string Size_Print { get; set; }
        [StringLength(10)]
        public string RDept_ID { get; set; }
        [StringLength(3)]
        public string SDept_ID { get; set; }
        [Required]
        [StringLength(10)]
        public string Size { get; set; }
        [Required]
        [StringLength(10)]
        public string Cause { get; set; }
        [Column(TypeName = "decimal(38, 0)")]
        public decimal? PO_Qty { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Plan_Start_ASY { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? MatlNoHave_At { get; set; }
        [StringLength(10)]
        public string MatlNoHave_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DownloadCSV_At { get; set; }
        [StringLength(10)]
        public string DownloadCSV_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Ready_At { get; set; }
        [StringLength(10)]
        public string Ready_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SReady_At { get; set; }
        [StringLength(10)]
        public string SReady_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Dispatch_At { get; set; }
        [StringLength(10)]
        public string Dispatch_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Cancel_At { get; set; }
        [StringLength(3)]
        public string Cancel_Code { get; set; }
        [StringLength(20)]
        public string Collect_No { get; set; }
        [StringLength(10)]
        public string HP_User { get; set; }
        [Column(TypeName = "date")]
        public DateTime? HP_Day { get; set; }
        [Column(TypeName = "decimal(38, 2)")]
        public decimal? Material_Sheet_Qty { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Supp_Schedule_Date { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Supp_Sche_SwitchDate { get; set; }
    }
}