// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vReplenishCheckSummary_2
    {
        [Required]
        [StringLength(1)]
        public string manuf { get; set; }
        [Column(TypeName = "date")]
        public DateTime exec_date { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [StringLength(40)]
        public string styna { get; set; }
        [StringLength(15)]
        public string style { get; set; }
        [StringLength(70)]
        public string custyle { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal? plan_qty { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? sum_bat_plan_qty { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? AccuFGIN { get; set; }
        [Column(TypeName = "date")]
        public DateTime? last_fgin_date { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? FGIN_Balance { get; set; }
        [StringLength(1)]
        public string ASL_Is_Complete { get; set; }
        [Column(TypeName = "decimal(38, 0)")]
        public decimal? CTL_Balance { get; set; }
        [StringLength(1)]
        public string CTL_Need_Replenish { get; set; }
        [Column(TypeName = "decimal(38, 0)")]
        public decimal? STC_Balance { get; set; }
        [StringLength(1)]
        public string STC_Need_Replenish { get; set; }
        [Column(TypeName = "decimal(38, 0)")]
        public decimal? STF_Balance { get; set; }
        [StringLength(1)]
        public string STF_Need_Replenish { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? STC_CheckDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ASL_CheckDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? STF_CheckDT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CTL_CheckDT { get; set; }
        public short? ClickCheckSortSTC { get; set; }
        public short? ClickCheckSortASL { get; set; }
        public short? ClickCheckSortSTF { get; set; }
        public short? ClickCheckSortCTL { get; set; }
    }
}