// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class vReplenishCheckLastDT
    {
        [Required]
        [StringLength(1)]
        public string manuf { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [Required]
        [StringLength(3)]
        public string ProdProcess { get; set; }
        public int? CheckTimes { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastCheckDT { get; set; }
    }
}