// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VTimeSquad
    {
        [Required]
        [StringLength(2)]
        public string Factory { get; set; }
        [Required]
        [StringLength(10)]
        public string Squad { get; set; }
        public TimeSpan? starttime { get; set; }
        public TimeSpan? endtime { get; set; }
        public int? hours { get; set; }
    }
}