// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_Cmpt_Workstation_DailyTransaction
    {
        [Required]
        [StringLength(15)]
        public string Workstation_Code { get; set; }
        [Column(TypeName = "date")]
        public DateTime Transaction_Date { get; set; }
        [Required]
        [StringLength(2)]
        public string Feedback_Stage { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? Transaction_Qty { get; set; }
    }
}