// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_Cmpt_FBSection_TotQty_Detail
    {
        [Required]
        [StringLength(15)]
        public string MO_No { get; set; }
        [Required]
        [StringLength(3)]
        public string MO_Batch { get; set; }
        [Required]
        [StringLength(5)]
        public string Process_No { get; set; }
        [Required]
        [StringLength(4)]
        public string Internal_Part_No { get; set; }
        [Required]
        [StringLength(4)]
        public string MO_Size { get; set; }
        [StringLength(4)]
        public string tsize { get; set; }
        [Column(TypeName = "decimal(7, 1)")]
        public decimal Total_Qty { get; set; }
        [Column(TypeName = "decimal(12, 5)")]
        public decimal? qty { get; set; }
        [Required]
        [StringLength(4)]
        public string Kind { get; set; }
    }
}