// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_Cmpt_Transaction_Summary_POBatchSize
    {
        [Required]
        [StringLength(1)]
        public string manuf { get; set; }
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [Required]
        [StringLength(5)]
        public string code { get; set; }
        [Required]
        [StringLength(4)]
        public string size { get; set; }
        [Required]
        [StringLength(4)]
        public string part { get; set; }
        [Column(TypeName = "decimal(12, 5)")]
        public decimal? Size_Plan_Qty { get; set; }
        [Required]
        [StringLength(4)]
        public string vendno { get; set; }
        [Required]
        [StringLength(1)]
        public string workshop { get; set; }
        [Required]
        [StringLength(10)]
        public string Feedback_Stage { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? Size_Trans_Qty { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? Bal_Trans_Qty { get; set; }
    }
}