// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_Cmpt_Summary_WorkshopSpin
    {
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [Required]
        [StringLength(10)]
        public string Feedback_Stage { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? A { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? B { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? C { get; set; }
        [Column(TypeName = "decimal(38, 1)")]
        public decimal? D { get; set; }
    }
}