// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_Cmpt_Process_FeedbackStage
    {
        public Guid ID { get; set; }
        [Required]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        [Required]
        [StringLength(5)]
        public string Process_No { get; set; }
        [StringLength(80)]
        public string Process_Name { get; set; }
        [Required]
        [StringLength(2)]
        public string Feedback_Stage { get; set; }
        [Required]
        [StringLength(250)]
        public string ENG_Description { get; set; }
        [StringLength(250)]
        public string CHT_Description { get; set; }
        [StringLength(250)]
        public string LCL_Description { get; set; }
        public int? Seq_of_Code { get; set; }
    }
}