// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_Cmpt_Transaction_Plus_351
    {
        public Guid Id { get; set; }
        [Required]
        [StringLength(20)]
        public string Transaction_No { get; set; }
        [Column(TypeName = "date")]
        public DateTime Transaction_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Transaction_At { get; set; }
        [Required]
        [StringLength(10)]
        public string Transaction_By { get; set; }
        [Required]
        [StringLength(15)]
        public string MO_No { get; set; }
        [Required]
        [StringLength(3)]
        public string MO_Batch { get; set; }
        [Required]
        [StringLength(2)]
        public string MO_Sequence { get; set; }
        [Required]
        [StringLength(5)]
        public string Process_No { get; set; }
        [Required]
        [StringLength(4)]
        public string Internal_Part_No { get; set; }
        [StringLength(20)]
        public string External_Part_No { get; set; }
        [Required]
        [StringLength(9)]
        public string Process_Material_No { get; set; }
        [Required]
        [StringLength(2)]
        public string Feedback_Stage { get; set; }
        public Guid? Work_Station { get; set; }
        [StringLength(10)]
        public string Work_Shift { get; set; }
        [Required]
        [StringLength(4)]
        public string MO_Size { get; set; }
        [StringLength(4)]
        public string Tooling_Size { get; set; }
        [Column(TypeName = "decimal(11, 1)")]
        public decimal Transaction_Qty { get; set; }
        [Required]
        [StringLength(4)]
        public string Supplier_No { get; set; }
    }
}