// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_EEP_FRIPO_EstExportDate
    {
        [Required]
        [StringLength(5)]
        public string Factory_ID { get; set; }
        [Required]
        [StringLength(20)]
        public string PO { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Plan_Ship_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Comfirmed_Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EstExportDate { get; set; }
    }
}