// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_HPBasis_HPOutsourceProcess_n71
    {
        [StringLength(1)]
        public string Company_No { get; set; }
        [StringLength(1)]
        public string Division_No { get; set; }
        [Required]
        [StringLength(10)]
        public string Factory_ID { get; set; }
        [Required]
        [StringLength(5)]
        public string Process_No { get; set; }
        [StringLength(80)]
        public string Description { get; set; }
        [StringLength(6)]
        public string HP_User { get; set; }
        [Column(TypeName = "date")]
        public DateTime? HP_Date { get; set; }
        [StringLength(1)]
        public string Is_Valid { get; set; }
        [StringLength(50)]
        public string Update_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}