// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_HP32Vendor
    {
        [Required]
        [StringLength(15)]
        public string manno { get; set; }
        [Required]
        [StringLength(3)]
        public string seq { get; set; }
        [Required]
        [StringLength(5)]
        public string code { get; set; }
        [Required]
        [StringLength(4)]
        public string part { get; set; }
        [Required]
        [StringLength(4)]
        public string size { get; set; }
        [Required]
        [StringLength(4)]
        public string vendno { get; set; }
        [StringLength(10)]
        public string Vendor_Name { get; set; }
    }
}