// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_HPBasis_HPDept_n15
    {
        [Required]
        [StringLength(3)]
        public string Dept_ID { get; set; }
        [StringLength(20)]
        public string Dept_C_Name { get; set; }
        [StringLength(20)]
        public string Dept_E_Name { get; set; }
        [StringLength(1)]
        public string Use_YN { get; set; }
    }
}