// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_HPBasis_HPCustomerBOM_j102
    {
        [Required]
        [StringLength(10)]
        public string Factory_ID { get; set; }
        [Required]
        [StringLength(4)]
        public string Customer_No { get; set; }
        [Required]
        [StringLength(20)]
        public string Style { get; set; }
        [Required]
        [StringLength(3)]
        public string Article { get; set; }
        [Required]
        [StringLength(20)]
        public string Part_No { get; set; }
        [StringLength(128)]
        public string Part_Name { get; set; }
    }
}