// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_HPBasis_HPUploadTime_ie27_1_log
    {
        [Required]
        [StringLength(10)]
        public string Factory_ID { get; set; }
        [Required]
        [StringLength(10)]
        public string Version { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Upload_Time { get; set; }
        [Required]
        [StringLength(50)]
        public string HP_User { get; set; }
        [Required]
        [StringLength(50)]
        public string Update_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}