// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_HPBasis_HPVendor_u01
    {
        [Required]
        [StringLength(4)]
        public string Vendor_No { get; set; }
        [StringLength(48)]
        public string Vendor_Desc { get; set; }
        [StringLength(10)]
        public string Vendor_Name { get; set; }
        [StringLength(12)]
        public string Boss { get; set; }
        [StringLength(16)]
        public string Tel { get; set; }
        [StringLength(12)]
        public string Fax_No { get; set; }
        [StringLength(20)]
        public string Uniform_ID { get; set; }
        [StringLength(2)]
        public string Type { get; set; }
        [Column(TypeName = "decimal(9, 0)")]
        public decimal? Ticket_Days { get; set; }
        [Column(TypeName = "decimal(9, 3)")]
        public decimal? Cash_Rate { get; set; }
        [StringLength(5)]
        public string Address_No { get; set; }
        [StringLength(60)]
        public string Address { get; set; }
        [StringLength(60)]
        public string Invoice_Address { get; set; }
        [StringLength(1)]
        public string Envelope_Print { get; set; }
        [StringLength(20)]
        public string Contact { get; set; }
        [StringLength(50)]
        public string Mail { get; set; }
        [StringLength(1)]
        public string Status_YN { get; set; }
        public int? Import_Upper_Day { get; set; }
        public int? Import_Bottom_Day { get; set; }
        public int? Import_Transfer_Day { get; set; }
        [StringLength(20)]
        public string In_Pay { get; set; }
        [StringLength(1)]
        public string Forecast { get; set; }
        [StringLength(3)]
        public string Amt_Code { get; set; }
        [StringLength(50)]
        public string Check_Title { get; set; }
        [Column(TypeName = "decimal(9, 0)")]
        public decimal? Discount_Day { get; set; }
        [StringLength(1)]
        public string Within { get; set; }
        [StringLength(4)]
        public string Country_ID { get; set; }
        [StringLength(1)]
        public string Pay_Type { get; set; }
        [Required]
        [StringLength(1)]
        public string Contract_Type { get; set; }
        [StringLength(48)]
        public string Seller { get; set; }
        [StringLength(48)]
        public string Shipper { get; set; }
        [StringLength(6)]
        public string HP_User { get; set; }
        [Column(TypeName = "date")]
        public DateTime? HP_Date { get; set; }
        [StringLength(50)]
        public string Update_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}