// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_HPBasis_HPPart_j06
    {
        [Required]
        [StringLength(4)]
        public string Part_No { get; set; }
        [StringLength(1)]
        public string Type { get; set; }
        [StringLength(60)]
        public string Part_C_Name { get; set; }
        [StringLength(60)]
        public string Part_E_Name { get; set; }
        [StringLength(1)]
        public string Outsource_Type { get; set; }
        [StringLength(6)]
        public string HP_User { get; set; }
        [Column(TypeName = "date")]
        public DateTime? HP_Date { get; set; }
        [StringLength(60)]
        public string Part_V_Name { get; set; }
        [StringLength(6)]
        public string HP_V_User { get; set; }
        [Column(TypeName = "date")]
        public DateTime? HP_V_Date { get; set; }
        [StringLength(50)]
        public string Update_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}