// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_HPBasis_HPMaterial_j13
    {
        [Required]
        [StringLength(10)]
        public string Material_ID { get; set; }
        [StringLength(240)]
        public string Material_C_Name { get; set; }
        [StringLength(240)]
        public string Material_E_Name { get; set; }
        [StringLength(4)]
        public string C_Unit { get; set; }
        [StringLength(4)]
        public string E_Unit { get; set; }
        [StringLength(10)]
        public string Purchase_Factory { get; set; }
        [StringLength(1)]
        public string Material_Type { get; set; }
        [StringLength(1)]
        public string Purchase_Type { get; set; }
        [StringLength(1)]
        public string Estimate_Type { get; set; }
        [StringLength(1)]
        public string Purchase_Print { get; set; }
        [StringLength(1)]
        public string Size_Print { get; set; }
        [StringLength(6)]
        public string HP_User { get; set; }
        [Column(TypeName = "date")]
        public DateTime? HP_Date { get; set; }
    }
}