// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_MES_Org_PDC
    {
        [Required]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        [Required]
        [StringLength(1)]
        public string PDC_ID { get; set; }
        [StringLength(40)]
        public string PDC_Desc { get; set; }
        [StringLength(40)]
        public string PDC_DescZW { get; set; }
        [StringLength(40)]
        public string PDC_DescVN { get; set; }
        [StringLength(10)]
        public string PDC_Sname { get; set; }
        [Required]
        [StringLength(3)]
        public string Line_ID { get; set; }
        [Required]
        [StringLength(4)]
        public string Dept_ID { get; set; }
        [StringLength(10)]
        public string Building { get; set; }
        public int? Line_Seq { get; set; }
        public int? Status { get; set; }
        [Required]
        [StringLength(4)]
        public string HP_Dept_ID { get; set; }
        [StringLength(1)]
        public string Block { get; set; }
        [StringLength(3)]
        public string Line_ID_2 { get; set; }
        public int? IsT1T3 { get; set; }
    }
}