// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_MES_POBatchOutputBalance
    {
        [StringLength(15)]
        public string MO_No { get; set; }
        [StringLength(3)]
        public string MO_Seq { get; set; }
        public int? PlanQty { get; set; }
        public int? OutputQty { get; set; }
        public int? BalanceQty { get; set; }
        [Required]
        [StringLength(1)]
        public string hadBalance { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Complete_Date { get; set; }
    }
}