// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_RackNET_Section_Setting
    {
        [Required]
        [StringLength(15)]
        public string Model { get; set; }
        [Required]
        [StringLength(20)]
        public string Article { get; set; }
        [StringLength(2)]
        public string PickupForm_Kind { get; set; }
        [Required]
        [StringLength(2)]
        public string Process_Code { get; set; }
        [Required]
        [StringLength(20)]
        public string Section { get; set; }
        public short Day_Deduction { get; set; }
    }
}