// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#24288;&#12289;&#29983;&#29986;&#32218;&#12289;&#29983;&#29986;&#37096;&#38272;&#32080;&#27083;&#38364;&#20418;&#27284;
    /// </summary>
    public partial class MES_Org
    {
        /// <summary>
        ///         /// 廠別
        /// </summary>
        [Key]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        /// <summary>
        ///         /// &#29983;&#29986;&#37096;
        /// </summary>
        [Key]
        [StringLength(1)]
        public string PDC_ID { get; set; }
        /// <summary>
        ///         /// &#29983;&#29986;&#32218;&#21029;
        /// </summary>
        [Key]
        [StringLength(3)]
        public string Line_ID { get; set; }
        /// <summary>
        ///         /// &#29983;&#29986;&#37096;&#38272;
        /// </summary>
        [Key]
        [StringLength(4)]
        public string Dept_ID { get; set; }
        /// <summary>
        ///         /// &#26847;&#21029;(&#23660;&#24615;)
        /// </summary>
        [StringLength(10)]
        public string Building { get; set; }
        public int? Line_Seq { get; set; }
        public int? Status { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(16)]
        public string Updated_By { get; set; }
        [Required]
        [StringLength(4)]
        public string HP_Dept_ID { get; set; }
        public int? IsAGV { get; set; }
        [StringLength(1)]
        public string Block { get; set; }
        [StringLength(5)]
        public string Line_ID_2 { get; set; }
        public int? IsT1T3 { get; set; }
    }
}