// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#29983;&#29986;&#37096;&#38272;&#20195;&#30908;&#27284;
    /// </summary>
    public partial class MES_Dept
    {
        /// <summary>
        ///         /// 廠別
        /// </summary>
        [Key]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        /// <summary>
        ///         /// &#29983;&#29986;&#37096;&#38272;&#21029;
        /// </summary>
        [Key]
        [StringLength(4)]
        public string Dept_ID { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;&#39006;&#21029;
        /// </summary>
        [StringLength(1)]
        public string Dept_Type { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;&#35498;&#26126;&#33521;&#25991;
        /// </summary>
        [StringLength(40)]
        public string Dept_Desc { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;&#35498;&#26126;&#20013;&#25991;
        /// </summary>
        [StringLength(40)]
        public string Dept_DescZW { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;&#35498;&#26126;&#36234;&#25991;
        /// </summary>
        [StringLength(40)]
        public string Dept_DescVN { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;&#31777;&#31281;&#33521;&#25991;
        /// </summary>
        [StringLength(10)]
        public string Dept_Sname { get; set; }
        /// <summary>
        ///         /// &#25152;&#23660;&#24037;&#24207;
        /// </summary>
        [StringLength(3)]
        public string PS_ID { get; set; }
        /// <summary>
        ///         /// &#21320;&#20241;&#26178;&#38291;
        /// </summary>
        [StringLength(1)]
        public string Lunch_Order { get; set; }
        /// <summary>
        ///         /// &#24037;&#27573;&#39006;&#21029;
        /// </summary>
        [StringLength(1)]
        public string Work_Center { get; set; }
        /// <summary>
        ///         /// &#26159;&#21542;&#39023;&#31034;&#22312;KB
        /// </summary>
        [StringLength(1)]
        public string Need_Bulletin { get; set; }
        /// <summary>
        ///         /// &#26159;&#21542;&#25293;&#29031;
        /// </summary>
        [StringLength(1)]
        public string Need_Camera { get; set; }
        /// <summary>
        ///         /// &#26159;&#21542;&#27298;&#35222;&#23433;&#26481;
        /// </summary>
        [StringLength(1)]
        public string Need_Andon { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(16)]
        public string Updated_By { get; set; }
    }
}