// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#20551;&#26085;&#35373;&#23450;&#27284;
    /// </summary>
    public partial class MES_Holiday
    {
        /// <summary>
        ///         /// 廠別
        /// </summary>
        [Key]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        /// <summary>
        ///         /// &#20551;&#26085;
        /// </summary>
        [Key]
        [Column(TypeName = "date")]
        public DateTime Holiday { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(6)]
        public string Updated_By { get; set; }
    }
}