// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#26085;&#29983;&#29986;&#35336;&#30059;&#27284;(HP&#36681;&#20837;)
    /// </summary>
    public partial class MES_MO
    {
        /// <summary>
        ///         /// 廠別
        /// </summary>
        [Key]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        /// <summary>
        ///         /// &#32218;&#21029;
        /// </summary>
        [StringLength(3)]
        public string Line_ID { get; set; }
        /// <summary>
        ///         /// &#25104;&#22411;&#32218;&#21029;
        /// </summary>
        [StringLength(3)]
        public string Line_ID_ASY { get; set; }
        /// <summary>
        ///         /// &#32068;&#24213;&#32218;&#21029;
        /// </summary>
        [StringLength(3)]
        public string Line_ID_STF { get; set; }
        /// <summary>
        ///         /// &#25104;&#22411;&#37096;&#38272;
        /// </summary>
        [StringLength(3)]
        public string Dept_ID { get; set; }
        /// <summary>
        ///         /// &#37341;&#36554;&#37096;&#38272;
        /// </summary>
        [StringLength(3)]
        public string Dept_ID_STC { get; set; }
        /// <summary>
        ///         /// &#32068;&#24213;&#37096;&#38272;
        /// </summary>
        [StringLength(3)]
        public string Dept_ID_STF { get; set; }
        /// <summary>
        ///         /// &#20225;&#21123;&#21934;&#34399;
        /// </summary>
        [StringLength(15)]
        public string MO_No { get; set; }
        /// <summary>
        ///         /// &#20225;&#21123;&#21934;&#25209;&#27425;
        /// </summary>
        [StringLength(3)]
        public string MO_Seq { get; set; }
        /// <summary>
        ///         /// &#36852;&#36681;&#34399;
        /// </summary>
        [Key]
        [StringLength(21)]
        public string Cycle_No { get; set; }
        /// <summary>
        ///         /// &#22411;&#39636;&#32232;&#34399;
        /// </summary>
        [StringLength(15)]
        public string Style_No { get; set; }
        /// <summary>
        ///         /// &#22411;&#39636;&#21517;&#31281;
        /// </summary>
        [StringLength(40)]
        public string Style_Name { get; set; }
        /// <summary>
        ///         /// &#33394;&#34399;
        /// </summary>
        [StringLength(10)]
        public string Color_No { get; set; }
        /// <summary>
        ///         /// &#20225;&#21123;&#21934;&#30446;&#27161;&#25976;
        /// </summary>
        public int? Plan_Qty { get; set; }
        /// <summary>
        ///         /// &#23526;&#38555;&#29986;&#37327;
        /// </summary>
        public int? UTN_Yield_Qty { get; set; }
        /// <summary>
        ///         /// &#37341;&#36554;&#29986;&#37327;
        /// </summary>
        public int? UTN_Yield_Qty_STC { get; set; }
        /// <summary>
        ///         /// &#32068;&#24213;&#29986;&#37327;
        /// </summary>
        public int? UTN_Yield_Qty_STF { get; set; }
        /// <summary>
        ///         /// &#32068;&#24213;&#36681;&#20986;&#25976;&#37327;
        /// </summary>
        public int? UTN_Forward_Qty_STF { get; set; }
        /// <summary>
        ///         /// &#37341;&#36554;&#36681;&#20986;&#25976;&#37327;
        /// </summary>
        public int? UTN_Forward_Qty_STC { get; set; }
        /// <summary>
        ///         /// &#37341;&#36554;&#20837;&#24235;&#25976;&#37327;
        /// </summary>
        public int? UTN_Yield_Qty_STC_In { get; set; }
        /// <summary>
        ///         /// &#25104;&#22411;&#25033;&#38283;&#22987;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Plan_Start_ASY { get; set; }
        /// <summary>
        ///         /// &#25104;&#22411;&#25033;&#32080;&#26463;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Plan_End_ASY { get; set; }
        /// <summary>
        ///         /// &#32068;&#24213;&#25033;&#38283;&#22987;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Plan_Start_STF { get; set; }
        /// <summary>
        ///         /// &#32068;&#24213;&#25033;&#32080;&#26463;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Plan_End_STF { get; set; }
        /// <summary>
        ///         /// &#37341;&#36554;&#25033;&#38283;&#22987;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Plan_Start_STC { get; set; }
        /// <summary>
        ///         /// &#37341;&#36554;&#25033;&#32080;&#26463;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Plan_End_STC { get; set; }
        /// <summary>
        ///         /// &#35009;&#26039;&#25033;&#38283;&#22987;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Plan_Start_CUT { get; set; }
        /// <summary>
        ///         /// &#35009;&#26039;&#25033;&#32080;&#26463;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Plan_End_CUT { get; set; }
        /// <summary>
        ///         /// &#25104;&#22411;&#23526;&#38555;&#38283;&#22987;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Act_Start_ASY { get; set; }
        /// <summary>
        ///         /// &#25104;&#22411;&#23526;&#38555;&#32080;&#26463;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Act_End_ASY { get; set; }
        /// <summary>
        ///         /// &#32068;&#24213;&#23526;&#38555;&#38283;&#22987;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Act_Start_STF { get; set; }
        /// <summary>
        ///         /// &#32068;&#24213;&#23526;&#38555;&#32080;&#26463;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Act_End_STF { get; set; }
        /// <summary>
        ///         /// &#37341;&#36554;&#23526;&#38555;&#38283;&#22987;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Act_Start_STC { get; set; }
        /// <summary>
        ///         /// &#37341;&#36554;&#23526;&#38555;&#32080;&#26463;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Act_End_STC { get; set; }
        /// <summary>
        ///         /// &#35009;&#26039;&#23526;&#38555;&#38283;&#22987;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Act_Start_CUT { get; set; }
        /// <summary>
        ///         /// &#35009;&#26039;&#23526;&#38555;&#32080;&#26463;&#26085;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Act_End_CUT { get; set; }
        /// <summary>
        ///         /// &#30446;&#30340;&#22320;
        /// </summary>
        [StringLength(50)]
        public string Destination { get; set; }
        /// <summary>
        ///         /// &#26368;&#24460;&#35037;&#31665;&#26085;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? Comfirm_Date { get; set; }
        /// <summary>
        ///         /// &#29983;&#29986;&#23395;&#31680;
        /// </summary>
        [StringLength(4)]
        public string Prod_Season { get; set; }
        /// <summary>
        ///         /// &#37325;&#40670;&#22411;&#39636;
        /// </summary>
        [StringLength(1)]
        public string Top_Model { get; set; }
        [StringLength(15)]
        public string Status { get; set; }
        public int? Received_Qty { get; set; }
        /// <summary>
        ///         /// &#26356;&#26032;&#26085;&#26399;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
        /// <summary>
        ///         /// &#26356;&#26032;&#20154;&#21729;
        /// </summary>
        [StringLength(16)]
        public string Updated_By { get; set; }
        /// <summary>
        ///         /// &#38928;&#35336;&#20986;&#36008;&#26085;,final&#35037;&#33337;&#26085;
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? CRD { get; set; }
    }
}