// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    /// <summary>
    ///     /// &#29983;&#29986;&#37096;&#38272;&#30446;&#27161;&#20027;&#27284;
    /// </summary>
    public partial class MES_Dept_Plan
    {
        /// <summary>
        ///         /// 廠別
        /// </summary>
        [Key]
        [StringLength(1)]
        public string Factory_ID { get; set; }
        /// <summary>
        ///         /// LEAN&#32218;
        /// </summary>
        [StringLength(3)]
        public string Line_ID { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;&#32232;&#34399; (ERP&#26159;&#22635;&#23531;&#25104;&#22411;&#32218;&#37096;&#38272;)
        /// </summary>
        [Key]
        [StringLength(3)]
        public string Dept_ID { get; set; }
        /// <summary>
        ///         /// &#20170;&#22825;&#29983;&#29986;&#26085; time&#37096;&#20998;00:00:00
        /// </summary>
        [Key]
        [Column(TypeName = "datetime")]
        public DateTime Plan_Date { get; set; }
        /// <summary>
        ///         /// &#26085;&#29983;&#29986;&#30446;&#27161;
        /// </summary>
        public int? Plan_Day_Target { get; set; }
        /// <summary>
        ///         /// &#26412;&#26085;&#27599;&#23567;&#26178;&#30446;&#27161;&#29986;&#37327;
        /// </summary>
        public int? Plan_Qty { get; set; }
        /// <summary>
        ///         /// &#32047;&#31309;&#26412;&#26085;&#29986;&#37327;
        /// </summary>
        public int? Plan_Qty_Cum { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;&#19981;&#33391;&#29575;&#35686;&#25106;&#32218;
        /// </summary>
        [Column(TypeName = "numeric(10, 2)")]
        public decimal? Def_Rate_UL { get; set; }
        /// <summary>
        ///         /// &#21069;&#19968;&#26085;&#20986;&#21220;&#20154;&#25976;
        /// </summary>
        public int? Last_Head_Cnt { get; set; }
        /// <summary>
        ///         /// &#26412;&#26085;&#20986;&#21220;&#20154;&#25976;
        /// </summary>
        public int? WT_Head_Cnt { get; set; }
        /// <summary>
        ///         /// &#26412;&#26085;&#21152;&#29677;&#20154;&#25976;
        /// </summary>
        public int? OT_Head_Cnt { get; set; }
        /// <summary>
        ///         /// &#26412;&#26085;&#32080;&#26463;&#21152;&#29677;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "time(5)")]
        public TimeSpan? OT_End_Time { get; set; }
        /// <summary>
        ///         /// &#20170;&#26085;UTN&#37096;&#38272;&#32047;&#35336;&#29986;&#37327;
        /// </summary>
        public int? UTN_Yield_Qty { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;UTN&#36948;&#25104;&#29575;
        /// </summary>
        [Column(TypeName = "numeric(10, 2)")]
        public decimal? UTN_Yield_Rate { get; set; }
        /// <summary>
        ///         /// &#20170;&#26085;UTN&#37096;&#38272;&#32047;&#35336;&#19981;&#33391;&#20214;&#25976;
        /// </summary>
        public int? UTN_Def_Qty { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;UTN&#21697;&#36074;&#33391;&#29575;(Right first time)
        /// </summary>
        [Column(TypeName = "numeric(10, 2)")]
        public decimal? UTN_RFT { get; set; }
        /// <summary>
        ///         /// &#20170;&#26085;UTN&#25237;&#20837;&#24037;&#26178;
        /// </summary>
        [Column(TypeName = "numeric(10, 2)")]
        public decimal? UTN_Total_ManHr { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;UTN &#35069;&#36896;&#25552;&#21069;&#26178;&#38291;(Manfacturing Lead Time)
        /// </summary>
        [Column(TypeName = "numeric(10, 2)")]
        public decimal? UTN_MLT { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;UTN&#22312;&#35069;&#21697;(Work In Process) WIP&#25976;&#37327;
        /// </summary>
        [Column(TypeName = "numeric(10, 2)")]
        public decimal? UTN_WIP { get; set; }
        /// <summary>
        ///         /// &#37096;&#38272;&#27599;&#20154;&#24037;&#23567;&#26178;&#29986;&#37327;
        /// </summary>
        [Column(TypeName = "numeric(10, 2)")]
        public decimal? UTN_PPH { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#26178;&#38291;
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
        /// <summary>
        ///         /// &#30064;&#21205;&#32773;
        /// </summary>
        [StringLength(16)]
        public string Updated_By { get; set; }
        /// <summary>
        ///         /// &#32317;&#24037;&#20316;&#20154;&#25976;
        /// </summary>
        public int? Total_Head_Cnt { get; set; }
        /// <summary>
        ///         /// &#24037;&#20316;&#26178;&#25976;
        /// </summary>
        [Column(TypeName = "numeric(10, 1)")]
        public decimal? Working_Hour { get; set; }
        /// <summary>
        ///         /// Biz_Key
        /// </summary>
        [StringLength(14)]
        public string Biz_Key { get; set; }
        public int? Qty1 { get; set; }
        public int? Qty2 { get; set; }
        public int? Qty3 { get; set; }
        public int? Qty4 { get; set; }
        public int? Qty5 { get; set; }
        /// <summary>
        ///         /// &#30070;&#22825;&#26368;&#24460;&#32218;&#19978;WIP&#25976;
        /// </summary>
        public int? Last_Qty { get; set; }
        /// <summary>
        ///         /// &#21628;&#21483;AGV
        /// </summary>
        public int? Send_Cars { get; set; }
        /// <summary>
        ///         /// MES212&#36664;&#20837;&#30340;&#23526;&#38555;&#24037;&#26178;
        /// </summary>
        [Column(TypeName = "numeric(10, 1)")]
        public decimal? Real_Hour { get; set; }
    }
}