// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class VW_Dept_PS_ID
    {
        [Required]
        [StringLength(3)]
        public string Line_ID { get; set; }
        [StringLength(3)]
        public string ASY { get; set; }
        [StringLength(3)]
        public string STI { get; set; }
        [StringLength(3)]
        public string PRE { get; set; }
        [StringLength(3)]
        public string STF { get; set; }
        [StringLength(1)]
        public string Line_Model { get; set; }
    }
}