// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class Materials
    {
        [Key]
        public long Id { get; set; }
        public DateTime CreateAt { get; set; }
        [StringLength(10)]
        public string Cunit { get; set; }
        [StringLength(10)]
        public string Eunit { get; set; }
        [Required]
        [StringLength(10)]
        public string Itnbr { get; set; }
        [Required]
        [StringLength(250)]
        public string NameCN { get; set; }
        [Required]
        [StringLength(250)]
        public string NameLC { get; set; }
        public DateTime UpdateAt { get; set; }
        public long VendorId { get; set; }

        [ForeignKey(nameof(VendorId))]
        [InverseProperty(nameof(Vendors.Materials))]
        public virtual Vendors Vendor { get; set; }
    }
}