// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPS_API.Models
{
    public partial class Vendors
    {
        public Vendors()
        {
            Materials = new HashSet<Materials>();
        }

        [Key]
        public long Id { get; set; }
        [StringLength(150)]
        public string Address { get; set; }
        public DateTime CreateAt { get; set; }
        public DateTime UpdateAt { get; set; }
        [Required]
        [StringLength(150)]
        public string Vendna { get; set; }
        [Required]
        [StringLength(150)]
        public string Vendno { get; set; }

        [InverseProperty("Vendor")]
        public virtual ICollection<Materials> Materials { get; set; }
    }
}